# Generated by Django 5.1.1 on 2024-10-14 12:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('22a34503-e9ce-45c6-b9b8-813ba7491505'), editable=False, primary_key=True, serialize=False),
        ),
    ]
